regions:
  - label: "EU (European Union)"
    value: "EU"
  - label: "US (United States)"
    value: "US"
  - label: "us-central1 (Iowa)"
    value: "us-central1"
  - label: "us-east1 (S. Carolina)"
    value: "us-east1"
  - label: "us-east4 (N. Virginia)"
    value: "us-east4"
  - label: "us-west1 (Oregon)"
    value: "us-west1"
  - label: "us-west2 (Los Angeles)"
    value: "us-west2"
  - label: "us-west4 (Las Vegas)"
    value: "us-west4"
  - label: "europe-west1 (Belgium)"
    value: "europe-west1"
  - label: "europe-west2 (London)"
    value: "europe-west2"
  - label: "europe-west3 (Frankfurt)"
    value: "europe-west3"
  - label: "europe-west4 (Netherlands)"
    value: "europe-west4"
  - label: "europe-west6 (Zürich)"
    value: "europe-west6"
  - label: "europe-north1 (Finland)"
    value: "europe-north1"
  - label: "asia-east1 (Taiwan)"
    value: "asia-east1"
  - label: "asia-northeast1 (Tokyo)"
    value: "asia-northeast1"
  - label: "asia-southeast1 (Singapore)"
    value: "asia-southeast1"
  - label: "australia-southeast1 (Sydney)"
    value: "australia-southeast1"

models:
  - label: "Gemini 3.5 Flash"
    value: "gemini-3.5-flash"
  - label: "Gemini 2.5 Pro"
    value: "gemini-2.5-pro"
  - label: "Gemini 2.5 Flash"
    value: "gemini-2.5-flash"
  - label: "Other (Enter manually)"
    value: "other"

prompts:
  titles: "prompts/titles.txt"
  descriptions: "prompts/descriptions.txt"

buckets:
  name: "${project}-feedgen"
